
hdfs:
  defaultFS: hdfs://mycluster
# spring cache 所用的redis配置
spring:
  redis:
    host: 127.0.0.1
    password: 123456
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1
        min-idle: 0
  cache:
    type: redis

